import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const browser=await chromium.launch({headless:true,executablePath:process.env.POSGRAM_BROWSER_PATH});
const errors=[];
await fs.mkdir('qa-evidence',{recursive:true});
async function open(width,height=1058){
 const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 await page.goto('http://127.0.0.1:4173/#/beranda',{waitUntil:'networkidle'});
 await page.evaluate(async()=>{const text=document.body.textContent;await Promise.all([400,500,550,600,650,700,750,800].map(weight=>document.fonts.load(`${weight} 14px Inter`,text)));await document.fonts.ready;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))});
 return page;
}
async function snapshot(page,name){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`qa-evidence/${name}.png`,fullPage:true,animations:'disabled'})}
const inviteButton=page=>page.getByRole('button',{name:'Bagikan Link Undangan',exact:true});
async function closeDialog(page){await page.getByRole('button',{name:'Tutup dialog',exact:true}).click()}
try{
 const layout=[];
 for(const width of [1920,1440,1428,1280,1024,834,768,390,320]){
  const page=await open(width);
  await page.getByRole('heading',{name:'Beranda',exact:true}).waitFor();
  assert.equal(await page.locator('.home-nav-active').getAttribute('aria-current'),'page');
  assert.equal(await page.locator('.home-workspace-chip').count(),0);
  assert.ok(await page.getByRole('heading',{name:'Persiapan TKA Lebih Terarah Bersama ASIQ',exact:true}).isVisible());
  assert.ok(await page.getByRole('img',{name:'Ilustrasi ASIQ',exact:true}).evaluate(el=>el.complete&&el.naturalWidth===1086));
  assert.equal(await page.getByRole('img',{name:'Ilustrasi kolaborasi guru dalam instansi',exact:true}).count(),1);
  assert.doesNotMatch(await page.locator('main').innerText(),/Kode|Gabung ke Instansi|44%|11 murid/);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const hero=await page.locator('.home-carousel').boundingBox(),invite=await page.locator('.home-invitation').boundingBox();
  if(width>1280){assert.ok(Math.abs(hero.height-invite.height)<1);assert.ok(Math.abs(hero.y-invite.y)<1);assert.ok(Math.abs(hero.width/invite.width-2.4)<.02)}
  else assert.ok(invite.y>=hero.y+hero.height+17);
  layout.push({width,heroHeight:Math.round(hero.height),inviteHeight:Math.round(invite.height)});
  if([1440,1428,1024,834,390,320].includes(width))await snapshot(page,`home-layout-asiq-${width}`);
  if(width===1428)await page.screenshot({path:'qa-evidence/home-layout-reference-1182.png',clip:{x:246,y:54,width:1182,height:613}});
  await page.getByRole('button',{name:'Slide berikutnya',exact:true}).click();
  await page.getByRole('heading',{name:'Pantau Kesiapan Murid dari Hasil Latihan TKA',exact:true}).waitFor();
  assert.equal(await page.locator('[aria-hidden="false"] .home-highlights li').count(),3);
  assert.equal(await page.getByRole('tab',{name:'Dashboard Kesiapan TKA',exact:true}).getAttribute('aria-selected'),'true');
  const nextHero=await page.locator('.home-carousel').boundingBox();assert.equal(nextHero.height,hero.height);
  const cta=await page.getByRole('link',{name:'Jelajahi Dasbor Kesiapan',exact:true}).boundingBox(),footer=await page.locator('.home-carousel-footer').boundingBox();
  assert.ok(cta.y+cta.height<=footer.y,`CTA overlaps carousel footer at ${width}`);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  if([1428,390,320].includes(width))await snapshot(page,`home-layout-dashboard-${width}`);
  await page.getByRole('button',{name:'Slide sebelumnya',exact:true}).click();
  await page.getByRole('tab',{name:'ASIQ',exact:true}).press('ArrowRight');
  assert.equal(await page.getByRole('tab',{name:'Dashboard Kesiapan TKA',exact:true}).getAttribute('aria-selected'),'true');
  await page.getByRole('tab',{name:'Dashboard Kesiapan TKA',exact:true}).press('Home');
  assert.equal(await page.getByRole('tab',{name:'ASIQ',exact:true}).getAttribute('aria-selected'),'true');
  await inviteButton(page).click();
  const dialog=page.getByRole('dialog',{name:'Bagikan Link Undangan',exact:true});await dialog.waitFor();
  assert.match(await dialog.innerText(),/SMP Negeri 1 Malang/);
  assert.ok(await dialog.getByRole('textbox',{name:'Link undangan instansi',exact:true}).getAttribute('readonly')!==null);
  assert.ok(await dialog.getByRole('button',{name:'Salin Link',exact:true}).isDisabled());
  assert.ok(await dialog.getByRole('button',{name:'Bagikan',exact:true}).isDisabled());
  assert.ok(await dialog.getByText('Link undangan belum tersedia.',{exact:true}).isVisible());
  if([1428,390].includes(width))await snapshot(page,`home-layout-invite-empty-${width}`);
  await dialog.getByRole('button',{name:'Tutup dialog',exact:true}).press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Link undangan instansi');
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
  assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Bagikan Link Undangan');
  await page.getByRole('button',{name:'Coba ASIQ Sekarang',exact:true}).click();
  await page.getByRole('dialog',{name:'ASIQ',exact:true}).waitFor();
  assert.ok(await page.getByText('Akses ASIQ belum tersedia.',{exact:true}).isVisible());
  await page.getByRole('dialog').getByRole('link',{name:'Jelajahi Dasbor Kesiapan',exact:true}).click();
  await page.getByRole('heading',{name:'Ringkasan Kesiapan Awal TKA',exact:true}).waitFor();
  assert.equal(await page.locator('.gauge-center>strong').innerText(),'44%');
  await page.goBack();await page.getByRole('heading',{name:'Beranda',exact:true}).waitFor();
  await page.reload({waitUntil:'networkidle'});await page.getByRole('heading',{name:'Beranda',exact:true}).waitFor();
  await page.getByRole('tab',{name:'Dashboard Kesiapan TKA',exact:true}).click();
  await page.getByRole('link',{name:'Jelajahi Dasbor Kesiapan',exact:true}).click();
  await page.getByRole('heading',{name:'Ringkasan Kesiapan Awal TKA',exact:true}).waitFor();
  await page.close();
 }
 const page=await open(390);
 await page.evaluate(async()=>{
  const {default:HomePage}=await import('/src/HomePage.jsx');
  const React=await import('/node_modules/.vite/deps/react.js'),ReactDOM=await import('/node_modules/.vite/deps/react-dom_client.js');
  const mount=document.createElement('div');document.body.replaceChildren(mount);
  const root=(ReactDOM.createRoot||ReactDOM.default.createRoot)(mount);
  window.renderHome=(workspace,images)=>root.render(React.default.createElement(HomePage,{workspace,images,onRetryInvitation:()=>window.retries++}));
  window.copied=[];window.retries=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.copied.push(value)}});
  Object.defineProperty(navigator,'share',{configurable:true,value:undefined});
  window.fixture={name:'Instansi Uji',permissions:['instansi.invite.share'],invitationStatus:'ready',invitationUrl:'https://example.com/invitations/instansi-uji',asiqUrl:'https://example.com/workspaces/asiq'};
  window.renderHome(window.fixture);
 });
 await page.getByRole('link',{name:'Coba ASIQ Sekarang',exact:true}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Coba ASIQ Sekarang',exact:true}).getAttribute('href'),'https://example.com/workspaces/asiq');
 await inviteButton(page).click();
 await page.getByRole('button',{name:'Salin Link',exact:true}).click();
 await page.getByText('Link undangan berhasil disalin.',{exact:true}).waitFor();
 assert.deepEqual(await page.evaluate(()=>window.copied),['https://example.com/invitations/instansi-uji']);
 await page.getByRole('button',{name:'Bagikan',exact:true}).click();
 const message=page.getByRole('textbox',{name:'Pesan untuk dibagikan',exact:true});await message.waitFor();
 assert.match(await message.inputValue(),/Instansi Uji.*POSGRAM.*ASIQ/);assert.match(await message.inputValue(),/https:\/\/example.com\/invitations\/instansi-uji/);
 await page.getByRole('button',{name:'Salin Pesan',exact:true}).click();await page.getByText('Pesan undangan berhasil disalin.',{exact:true}).waitFor();
 await snapshot(page,'home-layout-share-fixture-390');
 await page.evaluate(()=>window.renderHome({...window.fixture,invitationUrl:'https://example.com/invitations/updated'}));
 await page.waitForFunction(()=>document.querySelector('textarea')?.value.includes('/updated'));
 await closeDialog(page);
 await page.evaluate(()=>{window.shared=[];Object.defineProperty(navigator,'share',{configurable:true,value:async payload=>window.shared.push(payload)})});
 assert.equal(await page.evaluate(()=>window.shared.length),0);
 await inviteButton(page).click();await page.getByRole('button',{name:'Bagikan',exact:true}).click();
 await page.getByText('Link undangan berhasil dibagikan.',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.shared[0].url),'https://example.com/invitations/updated');
 await closeDialog(page);
 await page.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('Cancelled','AbortError')}}));
 await inviteButton(page).click();await page.getByRole('button',{name:'Bagikan',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.home-dialog-actions button[disabled]'));
 assert.equal(await page.locator('textarea').count(),0);assert.equal(await page.locator('.home-feedback').count(),0);
 await closeDialog(page);
 await page.evaluate(()=>window.renderHome({...window.fixture,invitationStatus:'loading'}));
 await inviteButton(page).click();await page.getByText('Menyiapkan link undangan…',{exact:true}).waitFor();
 assert.ok(await page.getByRole('button',{name:'Salin Link',exact:true}).isDisabled());
 await page.evaluate(()=>window.renderHome({...window.fixture,invitationStatus:'error',invitationError:'Undangan gagal dimuat.'}));
 await page.getByRole('alert').getByText('Undangan gagal dimuat.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Coba Lagi',exact:true}).click();assert.equal(await page.evaluate(()=>window.retries),1);
 await page.evaluate(()=>window.renderHome(window.fixture));
 await page.waitForFunction(()=>document.querySelector('.home-invitation-field input')?.value.includes('/instansi-uji'));
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new DOMException('Denied','NotAllowedError')}}}));
 await page.getByRole('button',{name:'Salin Link',exact:true}).click();await page.getByRole('alert').waitFor();
 assert.match(await page.getByRole('alert').innerText(),/salin secara manual/);
 await page.evaluate(()=>window.renderHome({...window.fixture,permissions:['instansi.invite.view']}));
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 assert.equal(await inviteButton(page).count(),0);assert.equal(await page.locator('.home-invitation').count(),0);
 assert.equal(await page.locator('.without-invitation').count(),1);
 assert.doesNotMatch(await page.locator('main').innerText(),/invitations|Undang Guru/);
 await page.evaluate(()=>window.renderHome({...window.fixture,name:'Instansi Berikutnya',invitationUrl:'javascript:alert(1)'}));
 await inviteButton(page).click();assert.ok(await page.getByRole('button',{name:'Salin Link',exact:true}).isDisabled());
 await closeDialog(page);
 await page.evaluate(()=>window.renderHome(window.fixture,{asiq:'/assets/posgram-logo.png',readiness:'/assets/posgram-logo.png',invitation:'/assets/posgram-logo.png'}));
 await page.getByRole('img',{name:'Ilustrasi ASIQ',exact:true}).waitFor();
 await page.getByRole('img',{name:'Ilustrasi Kolaborasi instansi',exact:true}).waitFor();
 assert.equal(await page.getByRole('img',{name:'Placeholder gambar ASIQ',exact:true}).count(),0);
 await page.getByRole('tab',{name:'Dashboard Kesiapan TKA',exact:true}).click();
 await page.getByRole('img',{name:'Ilustrasi Dashboard Kesiapan TKA',exact:true}).waitFor();
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('.home-slide').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
 await page.close();
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify(layout));
 console.log('Passed: nine viewport layouts, equal desktop card heights, stable manual carousel/keyboard, supplied hero assets and native collaboration visual, invitation link states/retry, copy/native share/cancellation/fallback, permission revocation, distinct ASIQ URL, image replacement, route/back/reload, focus, no overflow or page errors.');
}finally{await browser.close()}
